################################################################################
# Automatically-generated file. Do not edit or delete the file
################################################################################

APP\main.c

APP\Sess16\ASG1\ASS_PROG.c

APP\Sess16\ses.c

APP\Sess16\Task\ses.c

APP\Sess17\ses.c

APP\Sess18\ASG2\ASS_PROG.c

APP\Sess18\ses.c

APP\Sess18\TASKNEWCHARACTER\NEWCHARACTER_PROG.c

APP\Sess19\sess_PROG.c

APP\Sess19\TASKCALC\CALC_PROG.c

APP\Sess19\TASKLOGINSYSTEM\LOG_PROG.c

APP\Sess20\sess_PROG.c

APP\Sess22TI1\SESSTI1_PROG.c

APP\Sess21\SESS_PROG.c

APP\Sess21\TASK\TASK_PROG.c

APP\Sess22TI1\TASKCOUNTER\TASKCOUNTER_PROG.c

APP\Sess23CTC\PWM\PWM_PROG.c

APP\Sess23CTC\sess_PROG.c

APP\Sess24MOTOR\SERVO\SERVO_PROG.c

APP\Sess24MOTOR\sess_PROG.c

APP\Sess25WDT\sess_PROG.c

APP\Sess25WDT\TaskULTRASONIC\ULTRA_PROG.c

APP\Sess26UART\sess_PROG.c

APP\Sess26UART\TASKKPDUART\TASKKPDUART_PROG.c

APP\Sess27SPI\BLUTOTH\sess_PROG.c

APP\Sess27SPI\sess_PROG.c

APP\Sess28I2C\sess_PROG.c

APP\Sess29EEPROM\sess_PROG.c

APP\Sess29EEPROM\TASKEEPROMPASS\TASKEEPROMPASS_PROG.c

APP\Sess32\sess_PROG.c

APP\Sess32\TTL\sess_PROG.c

APP\Sess33FREERTOS\sess_PROG.c

FREERTOS\croutine.c

FREERTOS\event_groups.c

FREERTOS\heap_1.c

FREERTOS\list.c

FREERTOS\port.c

FREERTOS\queue.c

FREERTOS\stream_buffer.c

FREERTOS\tasks.c

FREERTOS\timers.c

HAL\7seg\SS_PROG.c

HAL\EEPROM\EEPROM_PROG.c

HAL\KPD\KPD_PROG.c

HAL\LCD\LCD_PROG.c

MCAL\ADC\ADC_PROG.c

MCAL\DIO\DIO_PROG.c

MCAL\EXT\EXT_PROG.c

MCAL\GI\GI_PROG.c

MCAL\I2C\I2C_PROG.c

MCAL\SPI\SPI_PROG.c

MCAL\TIMER0\TIMER0_PROG.c

MCAL\TIMER1\TIMER1_PROG.c

MCAL\UART\UART_PROG.c

MCAL\WDT\WDT_PROG.c

RTOS\RTOS.c

